apiVersion: v1
kind: Pod
metadata:
  name: aggregator
  labels:
    app: aggregator
spec:
  serviceAccountName: {{ if .Values.rbac.create }}aggregator{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
  containers:
  - name: aggregator
    image: {{ .Values.images.name }}:{{ .Values.images.aggregatorVersion }}
    imagePullPolicy: {{ .Values.imagePullPolicy }}
    env:
      - name: DISABLE_HTTP2
        value: "true"
    args:
      - -max-replicas={{ .Values.aggregator.maxReplicas }}
      - -logtostderr
      - -v={{ .Values.aggregator.logLevel }}
      - -interval={{ .Values.aggregator.interval }}
      - -loadbots-port=18080
      - -sleep={{ .Values.aggregator.sleep }}
