apiVersion: v1
kind: ReplicationController
metadata:
  name: webserver
spec:
  replicas: 1
  selector:
    app: webserver
  template:
    metadata:
      name: webserver
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: {{ .Values.images.name }}:{{ .Values.images.webserverVersion }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        args:
        - -port=80
        ports:
        - name: http-port
          protocol: TCP
          containerPort: 80
        resources:
          requests:
            cpu: {{ .Values.cpuRequests.webserver }}
# 调度策略，看需求开启
#      nodeSelector:
#        kubernetes.io/hostname: cn-beijing.172.16.0.69
