imagePullPolicy: Always
images:
  name: registry.cn-beijing.aliyuncs.com/log-service/logtail
  loadbotVersion: "ebpf-test-client"
  webserverVersion: "ebpf-test-web-server"
  aggregatorVersion: "ebpf-test-aggregator"

cpuRequests:
  loadbot: "100m"
  webserver: "100m"

rbac:
  create: true
  serviceAccountName: default

aggregator:
  maxReplicas: 100
  logLevel: 2
  interval: 5m
  sleep: 10s

loadbot:
  rate: 10000
  workers: 10
  duration: 20s