imagePullPolicy: Always
images:
  name: registry.cn-beijing.aliyuncs.com/log-service/logtail
  loadbotVersion: "ebpf-test-client"
  webserverVersion: "ebpf-test-web-server"
  aggregatorVersion: "ebpf-test-aggregator"

cpuRequests:
  loadbot: "100m"
  webserver: "100m"

rbac:
  create: true
  serviceAccountName: default

aggregator:
  maxReplicas: 100
  logLevel: 2
  # 不同测试场景直接间隔
  interval: 30s
  # 多少秒后启动流量
  sleep: 30s

loadbot:
# QPS
# 5W
#  rate: 1250
# 10W
#  rate: 2500
# 20W
  rate: 5000
  workers: 10
  # 压测时间
  duration: 300s
